Ht 2503 dataden
hathitrust/audit pull request #1
Opened 2020-09-02 16:26 UTC by moseshll

More work in progress. Zip and METS check (`sub check_zip()`) should perhaps be removed or made optional depending on how pedantic we wish to be.

2020-09-02 17:46 UTC, aelkiss commented on audit_data_den.pl
> +my $last_run = '0000-00-00 00:00:00';
Wondering if it might be easier to just record when the program started and at the end look for items that haven't been updated since the start of the run?

2020-09-02 17:47 UTC, aelkiss commented on audit_data_den.pl
> +  #next if $line =~ /\Qpre_uplift.mets.xml\E/;
We can remove this line.

2020-09-02 17:51 UTC, aelkiss commented on audit_data_den.pl
> +sub check_zip {
Could we move this to a separate script that accepts just a single path? For time time being we don't want to ever accidentally do a bulk read of items under data den (since it might trigger large numbers of recalls of items from tape)

2020-09-02 17:51 UTC, aelkiss requested changes
Looks good except zipcheck needs to be excised so we don't accidentally recall large numbers of items from tape. Once that's done I can give it a try on the real thing and see if there any issues.

2020-09-03 16:06 UTC, moseshll commented on audit_data_den.pl
> +my $last_run = '0000-00-00 00:00:00';
To clarify, you recommend swapping out the `select max(lastchecked) from feed_backups` altogether? If so then I'd probably just swap in `select now()`. (I'm leery of mixing MariaDB and system times because of the potential for time zone madness.)

2020-09-03 16:08 UTC, aelkiss commented on audit_data_den.pl
> +my $last_run = '0000-00-00 00:00:00';
Good point. I think `select now()` makes sense.

2020-09-03 17:09 UTC, moseshll commented on audit_data_den.pl
> +sub check_zip {
Spun off in next PR.

2020-09-03 17:13 UTC, moseshll commented
I think this may be ready to unleash on real data with the new PR.

2020-09-03 19:06 UTC, aelkiss commented on audit_data_den_zipfile.pl
> +check_zip($pathinfo);
we should update feed_audit and set lastmd5check = NOW(), md5check_ok = 1 if it succeeded and lastmd5check = NOW(), md5check = 0 if it failed.

2020-09-03 19:10 UTC, aelkiss commented on run_data_den_audit.sh
> +export HTFEED_CONFIG=$SDRROOT/feed/etc/config_dev.yaml
Let's set `HTFEED_CONFIG` and `FEED_HOME` only if they aren't already set. One way to do this is (allegedly):

```bash
: ${HTFEED_CONFIG:=$SDRROOT/feed/etc/config_dev.yaml}
: ${FEED_HOME:=$SDRROOT/feed}
```

2020-09-03 19:16 UTC, aelkiss commented on audit_data_den.pl
> +my $select_unchecked =
Probably worth at least extracting this part as a function. I'm waffling about how to actually run this in production; this might make more sense as a more explicitly structured separately-run step, which would also make it easier to try to parallelize the first part of the checking (just run several copies at different parts of the pairtree)

2020-09-03 20:41 UTC, moseshll commented on audit_data_den_zipfile.pl
> +check_zip($pathinfo);
I'm reading `ht_repository.feed_audit` as `ht_repository.feed_backups`, lemme know if that is not OK.

2020-09-03 21:04 UTC, aelkiss approved these changes

2020-09-03 21:04 UTC, merged